[package]
name = "cups-client"
version = "0.1.0"
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
ipp.workspace = true
futures.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio = { version = "1.49", default-features = false, features = ["time"] }
async-stream = "0.3"

[dev-dependencies]
tokio = { version = "1.49", default-features = false, features = ["macros", "rt"] }
